-- client.sql

CREATE TABLE PARTY.CLIENT (
    SEQUENCEID INT PRIMARY KEY,
    CLIENTID VARCHAR(128) UNIQUE,
    PASSWORD VARCHAR(128),
    CLIENTEMAIL VARCHAR(512) UNIQUE,
    KEYWORD VARCHAR(2056)
);

INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (1,'tester','test','test@test.net','연수구/3,서구/2,a/1,남동구/1,미추홀구/1,돈까스/1,자연/1,음식/1,쇼핑/1,계양구/1,레저/1');
INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (2,'keyword','keyword','keyword@key.key','부평구/1,관광/1,레저/1,음식/1');
INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (3,'update','test','update@da.com','커피/2,부평구/1,레저/1');
INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (4,'finaltest','1234','finaltest@test.com','계양구/1,중구/1,자연/1,음식/1');
INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (5,null,null,null,'계양구/1,동구/1,미추홀구/1,자연/1,쇼핑/1');
INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (21,null,null,null,null);
INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (22,null,null,null,'연수구/1,남동구/1,부평구/1,계양구/1,서구/1,동구/1,중구/1,미추홀구/1,강화군/1,옹진군/1,관광/1,자연/1,레저/1,쇼핑/1,음식/1,숙박/1,문화/1');
INSERT INTO PARTY.CLIENT (SEQUENCEID, CLIENTID, PASSWORD, CLIENTEMAIL, KEYWORD) VALUES (41,'party','party','party@party.com','서구/1,미추홀구/1,자연/1,음식/1,연수구/1');