-- searchinput.sql

CREATE TABLE PARTY.SEARCHINPUT (
    SEQUENCEID INT,
    CATEGORY VARCHAR(256),
    KEYWORD VARCHAR(256),
    ADDRESS VARCHAR(256)
);

INSERT INTO PARTY.SEARCHINPUT (SEQUENCEID, CATEGORY, KEYWORD, ADDRESS) VALUES (1,null,null,'남동구');
INSERT INTO PARTY.SEARCHINPUT (SEQUENCEID, CATEGORY, KEYWORD, ADDRESS) VALUES (2,null,null,'서구');
INSERT INTO PARTY.SEARCHINPUT (SEQUENCEID, CATEGORY, KEYWORD, ADDRESS) VALUES (3,null,null,'계양구');
-- (나머지 INSERT 문은 생략되었습니다)
INSERT INTO PARTY.SEARCHINPUT (SEQUENCEID, CATEGORY, KEYWORD, ADDRESS) VALUES (446,null,'가을',null);
INSERT INTO PARTY.SEARCHINPUT (SEQUENCEID, CATEGORY, KEYWORD, ADDRESS) VALUES (447,null,null,'');